const GET_ALL = 'GET_ALL';
const GET_ONE = 'GET_ONE';
const GET_SOME = 'GET_SOME';
const GET_GENRES = 'GET_GENRES' ;
const POST_NEW = 'POST_NEW';
const EXIT_DETAIL = 'EXIT_DETAIL';
const EXIT_SEARCH = 'EXIT_SEARC';
const SAVE_SEARCH = 'SAVE_SEARCH'
module.exports={
    GET_ALL,
    GET_ONE,
    GET_SOME,
    GET_GENRES,
    POST_NEW,
    EXIT_DETAIL,
    EXIT_SEARCH,
    SAVE_SEARCH
}