export const GET_ALL = 'GET_ALL';
export const GET_ONE = 'GET_ONE';
export const GET_SOME = 'GET_SOME';
export const GET_GENRES = 'GET_GENRES' ;
export const POST_NEW = 'POST_NEW';
export const EXIT_DETAIL = 'EXIT_DETAIL';
export const EXIT_SEARCH = 'EXIT_SEARC';
export const SAVE_SEARCH = 'SAVE_SEARCH';
export const FILTER_GENRE = 'FILTER_GENRE';
export const EXIT_FILTER = 'EXIT_FILTER';
export const FILTER_ORDER = 'FILTER_ORDER';
export const FILTER_ORIGIN ='FILTER_ORIGIN';
export const POST_RESET = 'POST_RESET'
